title: Long Yan Tang # your name (or website title) here
logo: "/images/me_round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  First description 
  <br><br>
  I am a recent Masters graduate in Applied Social Data Science at the London School of Economics and Political Science (LSE). I am actively looking for opportunities in management and technology consulting
  As an intern at Deloitte Consulting (Digital), I discovered my interests in consulting and data analytics. I find the process of project-based problem solving intellectually stimulating. I have a good command of data analysis tools such as Python, R, and SQL. As well as data visualisation tools such as Tableau, Ggplot2, and Matplotlib. During my internship in the Equity Investment Department in AIA, my team created an MSCI forecasting model with highly satisfactory results. I am actively seeking opportunities in relevant data-driven roles.
  <br><br>
  <a href="https://www.linkedin.com/in/ly-tang/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
